//  Generated by slacker
import http from "./http";

import store from "@/store";

import * as cookie from "@/utils/cookie";

export function Take(id) {
  return http.get(`/api/{{.LowerName}}/${id}`);
}

export function List(query) {
  return http.get("/api/{{.LowerName}}", {
    params: query
  });
}

export function Create(body) {
  return http.post("/api/{{.LowerName}}", body);
}

export function Update(id, body) {
  return http.put(`/api/{{.LowerName}}/${id}`, body);
}

export function Patch(id, body) {
  return http.patch(`/api/{{.LowerName}}/${id}`, body);
}

export function Delete(id) {
  return http.delete(`/api/{{.LowerName}}/${id}`);
}

export function BatchDelete(query) {
  return http.delete(`/api/{{.LowerName}}`, {
    params: query
  });
}

export function BatchPatch(query, body) {
  return http.patch(`/api/{{.LowerName}}`, body, {
    params: query
  });
}

export function BatchUpdate(query, body) {
  return http.put(`/api/{{.LowerName}}`, body, {
    params: query
  });
}

export function Import(file) {
  var form = new FormData();
  form.append("file", file, file.name);
  return http.post(`/api/import/{{.LowerName}}`, form, {
    headers: {
      "Content-Type": "multipart/form-data"
    }
  });
}

export function Export() {
  var url =
    process.env.VUE_APP_BaseURL +
    "/api/export/{{.LowerName}}?access_token=" +
    store.state.token;
  location.href = url;
}

export function WebSocket() {
  const token = cookie.getToken();
  let host = "";
  if (process.env.VUE_APP_BaseURL == "") {
    host = `ws://${location.host}`;
  } else {
    host = process.env.VUE_APP_BaseURL.replace("http", "ws");
  }
  return `${host}/api/websocket/ssh?access_token=${token}`;
}
