//Generated by slacker
//table {{.Name}}
//SQL
//{{.StdSQL}}
//NamedSQL -> github.com/jmoiron/sqlx
//{{.NamedSQL}}
//Columns
//{{.SQLColumns}}
package {{.LowerName}}

import (
	"{{"gosrc/models"| .ImportLibrary}}"
	{{if .IsUserTable}}
		"encoding/json"
	{{end}}
)
const(
	StateOK=0
	StateDel=1
)

func init() { models.AutoMigrate({{.CamelCaseName}}{}) }
 
type {{.CamelCaseName}} struct{
    {{range $i,$col:=.Columns}} {{$col.CamelCaseName}} {{$col.Type}} {{$col.Tag}} {{$col.Comment}}
    {{end}}
}

{{if .IsUserTable}}
func ({{.Initials}} {{.CamelCaseName}}) MarshalJSON() ([]byte, error) {
	type tmp {{.CamelCaseName}}
	{{.Initials}}.{{.PasswordColumn.CamelCaseName}} = ""
	return json.Marshal(tmp({{.Initials}}))
}
{{end}}

func ({{.Initials}} {{.CamelCaseName}}) TableName() string { 
	return "{{.Name}}"
}

type Search struct {
	{{.CamelCaseName}}
	Offset uint64 `json:"offset" form:"offset"`
	Limit uint64 `json:"limit" form:"limit"`
}
  