settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: {{.ProjectName}}
  path: .
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    - yaml
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    - node_modules
    - dist
    - src
