debug: true

gin:
  port: :{RandPort}
  gzip: true
  log: stdout

jwt:
  expirein: 86400 

cors:
  enable: true

{{if eq .HasUserTable false}}
auth:
  user: admin
  password: admin
{{end}}

mysql:
  host: {{.MysqlConfig.Addr}}
  user: {{.MysqlConfig.User}}
  password: "{{.MysqlConfig.Passwd}}"
  db: {{.MysqlConfig.DBName}}

meta:
  logo: {{.ProjectName}}
  title: {{.ProjectName}}
