debug: true

gin:
  port: 0.0.0.0:{RandPort}
  gzip: true
  log: stdout
  cors: true

{{if eq .HasUserTable false}}
auth:
  user: admin
  password: admin
{{end}}

mysql:
  host: {{.MysqlConfig.Addr}}
  user: {{.MysqlConfig.User}}
  password: "{{.MysqlConfig.Passwd}}"
  db: {{.MysqlConfig.DBName}}

meta:
  logo: {{.ProjectName}}
  title: {{.ProjectName}}
