//Generated by slacker
package service

import (
	"crypto/md5"
	"encoding/hex"
	"{{.ProjectName}}/gosrc/dao"
	"{{.ProjectName}}/gosrc/models/{{.UserTable.Name}}"
)

type ServiceOption func(service *Service)

func WithDao(d *dao.Dao)ServiceOption  {
	d.Init()
	return func(s *Service) {
		s.dao = d
	}
}
 
type Service struct {
	dao *dao.Dao
}

func New(options ...ServiceOption) *Service {
	s:= &Service{}
	for _,option:=range options{
		option(s)
	}
	s.init()
	return s
}

func (s *Service)init()  {
	{{if .HasUserTable}}
user:={{.UserTable.LowerName}}.{{.UserTable.CamelCaseName}}{
	{{.UserTable.UsernameColumn.CamelCaseName}}:"admin",
	{{.UserTable.PasswordColumn.CamelCaseName}}:"admin",
} 
s.Create{{.UserTable.CamelCaseName}}(&user)
{{end}}
}

func MD5(s string) string {
	m := md5.New()
	m.Write([]byte(s))
	return hex.EncodeToString(m.Sum(nil))
}