//Generated by slacker
package service

import (
	"errors"
	"{{.ProjectPath}}/gosrc/dao"
	"github.com/jmoiron/sqlx"
	"{{.ProjectPath}}/gosrc/models/{{.UserTable.Name}}"
)

 
type Service struct {
	dao *dao.Dao
}

func New(db *sqlx.DB) *Service {
	d:=dao.New(db)
	d.Init()
	s:= &Service{
		dao: d,
	}
	s.init()
	return s
}

func (s *Service)init()  {
	{{if .HasUserTable}}
user:={{.UserTable.LowerName}}.{{.UserTable.CamelCaseName}}{
	{{.UserTable.UsernameColumn.CamelCaseName}}:"admin",
	{{.UserTable.PasswordColumn.CamelCaseName}}:"admin",
} 
s.Create{{.UserTable.CamelCaseName}}(user)
{{end}}
}