//Generated by slacker
package service

import (
	"crypto/md5"
	"encoding/hex"
	"golang.org/x/crypto/bcrypt"
	"{{.ProjectName}}/gosrc/dao"
	"{{.ProjectName}}/gosrc/models/{{.UserTable.Name}}"
	"github.com/lixiangzhong/base64Captcha"
)

type ServiceOption func(service *Service)

func WithDao(d *dao.Dao)ServiceOption  {
	return func(s *Service) {
		s.dao = d
	}
}
 
type Service struct {
	dao *dao.Dao
}

func New(options ...ServiceOption) *Service {
	s:= &Service{}
	for _,option:=range options{
		option(s)
	}
	s.init()
	return s
}

func (s *Service)init()  {
	{{if .HasUserTable}}
user:={{.UserTable.LowerName}}.{{.UserTable.CamelCaseName}}{
	{{.UserTable.UsernameColumn.CamelCaseName}}:"admin",
	{{.UserTable.PasswordColumn.CamelCaseName}}:"admin",
} 
s.Create{{.UserTable.CamelCaseName}}(&user)
{{end}}
}

func MD5(s string) string {
	m := md5.New()
	m.Write([]byte(s))
	return hex.EncodeToString(m.Sum(nil))
}

func (*Service) EncryptPassword(password string) string {
	password = MD5(password)
	hashd, _ := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	return string(hashd)
}

func (*Service) ValidPassword(password, encryptedpwd string) bool {
	password = MD5(password)
	return nil == bcrypt.CompareHashAndPassword([]byte(encryptedpwd), []byte(password))
}

func VerifyCaptcha(captchaid,captchaval string) bool {
	return base64Captcha.VerifyCaptcha(captchaid, captchaval)
}
